name: validate-tf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-tf:
    uses: trussworks/shared-actions/.github/workflows/validate-tf.yml@96186a9bbe353f1c0cd876e9a5c9c3de24f29851 # v0.0.4
